record(ai, "$(crate)_sensor$(sensor)/temperature")
{
    field(DTYP,"Snmp")
    field(INP,"@$(HOST) $(COMMUNITY) $(W)::sensorTemperature.temp$(sensor) INTEGER: 100 i")
    field(SCAN,".2 second")
    field(EGU,"degC")
    field(DESC,"current")
    field(MDEL,"0.1")
    field(ADEL,"0.1")
    field(PREC, "1")
    field(HIHI,"125")
    field(HIGH,"100")
    field(LOW,"-1")
    field(LOLO,"-1")
    field(LLSV, "NO_ALARM")
    field(LSV, "NO_ALARM")
    field(HSV, "MINOR")
    field(HHSV, "MAJOR")
}