file db/channel_slot1-3.tpl{
 pattern {module, device, slot, channel, Ihihi, Ihhsv, Ihigh, Ihsv, Ilow, Ilsv, Ilolo, Illsv, Vhihi, Vhhsv, Vhigh, Vhsv, Vlow, Vlsv, Vlolo, Vllsv}
       {0, TPC1_pacFAN, 2, 0, 0.65, MAJOR, 0.625, MINOR, -1.0, MINOR, -1.0, MAJOR, 12.5, MAJOR, 9.75, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {0, TPC2_pacFAN, 2, 1, 0.65, MAJOR, 0.625, MINOR, -1.0, MINOR, -1.0, MAJOR, 12.5, MAJOR, 9.75, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {0, Interlock, 2, 2, 0.65, MAJOR, 0.575, MINOR, -1.0, MINOR, -1.0, MAJOR, 5.2, MAJOR, 5.1, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {0, pac_res3, 2, 3, 1.0, NO_ALARM, 0.84, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM, 5.0, NO_ALARM, 4.16, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM}
       {0, TPC1_PACMAN, 3, 0, 2.75, MAJOR, 2.625, MINOR, -1.0, MINOR, -1.0, MAJOR, 28.0, MAJOR, 26.005, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {0, TPC2_PACMAN, 3, 1, 2.75, MAJOR, 2.625, MINOR, -1.0, MINOR, -1.0, MAJOR, 28.0, MAJOR, 26.005, MINOR, -1.0, MINOR, -1.0, MAJOR}
}
