file db/channel_slot1-3.tpl{
 pattern {module, device, slot, channel, Ihihi, Ihhsv, Ihigh, Ihsv, Ilow, Ilsv, Ilolo, Illsv, Vhihi, Vhhsv, Vhigh, Vhsv, Vlow, Vlsv, Vlolo, Vllsv}
       {2, TPC1_pacFAN, 2, 0, 0.085, MAJOR, 0.0825, MINOR, -1.0, MINOR, -1.0, MAJOR, 25.0, MAJOR, 24.5, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {2, TPC2_pacFAN, 2, 1, 0.085, MAJOR, 0.0825, MINOR, -1.0, MINOR, -1.0, MAJOR, 25.0, MAJOR, 24.5, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {2, pac_res2, 2, 2, 1.0, NO_ALARM, 0.84, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM, 5.0, NO_ALARM, 4.16, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM}
       {2, pac_res3, 2, 3, 1.0, NO_ALARM, 0.84, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM, 5.0, NO_ALARM, 4.16, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM}
       {2, TPC1_PACMAN, 3, 0, 2.45, MAJOR, 2.35, MINOR, -1.0, MINOR, -1.0, MAJOR, 36.00, MAJOR, 30.005, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {2, TPC2_PACMAN, 3, 1, 2.45, MAJOR, 2.35, MINOR, -1.0, MINOR, -1.0, MAJOR, 36.00, MAJOR, 30.005, MINOR, -1.0, MINOR, -1.0, MAJOR}
}
