file db/channel_slot1-3.tpl{
 pattern {module, device, slot, channel, Ihihi, Ihhsv, Ihigh, Ihsv, Ilow, Ilsv, Ilolo, Illsv, Vhihi, Vhhsv, Vhigh, Vhsv, Vlow, Vlsv, Vlolo, Vllsv}
       {0, RTD_1, 1, 0, 1.0, MAJOR, 0.84, MINOR, -1.0, MINOR, -1.0, MAJOR, 5.2, MAJOR, 5.15, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {0, RTD_2, 1, 1, 1.0, MAJOR, 0.84, MINOR, -1.0, MINOR, -1.0, MAJOR, 5.2, MAJOR, 5.15, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {0, RTD_3, 1, 2, 1.0, NO_ALARM, 0.84, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM, 5.2, NO_ALARM, 5.15, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM}
       {0, RTD_4, 1, 3, 1.0, NO_ALARM, 0.84, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM, 5.2, NO_ALARM, 5.15, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM}
}
