file db/channel_slot1-3.tpl{
 pattern {module, device, slot, channel, Ihihi, Ihhsv, Ihigh, Ihsv, Ilow, Ilsv, Ilolo, Illsv, Vhihi, Vhhsv, Vhigh, Vhsv, Vlow, Vlsv, Vlolo, Vllsv}
       {3, RTD, 1, 4, 1.05, MAJOR, 1.025, MINOR, -1.0, MINOR, -1.0, MAJOR, 5.5, MAJOR, 5.3, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {3, RTD_2, 1, 5, 1.0, NO_ALARM, 0.84, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM, 5.2, NO_ALARM, 5.15, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM}
       {3, RTD_3, 1, 6, 1.0, NO_ALARM, 0.84, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM, 5.2, NO_ALARM, 5.15, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM}
       {3, RTD_4, 1, 7, 1.0, NO_ALARM, 0.84, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM, 5.2, NO_ALARM, 5.15, NO_ALARM, -1.0, NO_ALARM, -1.0, NO_ALARM}
}
