file db/channel_slot0.tpl{
 pattern {module, device, channel, Ihihi, Ihhsv, Ihigh, Ihsv, Ilow, Ilsv, Ilolo, Illsv, Vhihi, Vhhsv, Vhigh, Vhsv, Vlow, Vlsv, Vlolo, Vllsv}
       {2, VGA_Card_1, 0, 1.55, MAJOR, 1.525, MINOR, -1.0, MINOR, -1.0, MAJOR, 5.5, MAJOR, 5.25, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {2, VGA_Card_2, 1, 1.55, MAJOR, 1.525, MINOR, -1.0, MINOR, -1.0, MAJOR, 5.5, MAJOR, 5.25, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {2, VGA_Card_3, 2, 1.55, MAJOR, 1.525, MINOR, -1.0, MINOR, -1.0, MAJOR, 5.5, MAJOR, 5.25, MINOR, -1.0, MINOR, -1.0, MAJOR}
       {2, VGA_Card_4, 3, 1.55, MAJOR, 1.525, MINOR, -1.0, MINOR, -1.0, MAJOR, 5.5, MAJOR, 5.25, MINOR, -1.0, MINOR, -1.0, MAJOR}
}
